### PR TITLE
Lazily create di

### PR DESCRIPTION
**Pull request by barmac**
Contains https://github.com/bpmn-io/dmn-migration-utility/pull/4 and previous PRs.

### CODE REVIEW

**Comment by nikku** [comment]
Suggestion: Add a `.travis.yml` so we get CI test coverage.

**Comment by barmac** [comment]
> Suggestion: Add a `.travis.yml` so we get CI test coverage.

I'll do that, however the tests will fail until a proper version of dmn-moddle is installed.

**Comment by nikku** [comment]
> however the tests will fail until a proper version of dmn-moddle is installed.

A good reminder of what to do first :wink: :wine_glass:.

**Comment by barmac** [comment]
:+1:

**Pull request merged**
